services:
  - type: web
    name: livestock-app
    env: docker
    region: ohio
    plan: free

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_URL
        value: https://livestock-app-6vlg.onrender.com

      - key: ASSET_URL
        value: https://livestock-app-6vlg.onrender.com

      - key: APP_DEBUG
        value: false

      - key: APP_KEY
        generateValue: true

      - key: LOG_CHANNEL
        value: stderr

      - key: DB_CONNECTION
        value: pgsql

      - key: DB_SSLMODE
        value: require

      - key: DB_HOST
        sync: false

      - key: DB_PORT
        value: "5432"

      - key: DB_DATABASE
        sync: false

      - key: DB_USERNAME
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: GOOGLE_CLIENT_ID
        sync: false

      - key: GOOGLE_CLIENT_SECRET
        sync: false

      - key: GOOGLE_REDIRECT_URI
        value: https://livestock-app-6vlg.onrender.com/auth/google/callback